### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does

### ISSUE THREAD

**Issue by lgdelacruz92** [raulfdm/generator-react-component-library#47]
### I am submitting a ...

Bug Report

### Current Behavior
Issues using react-component-library and I get a `trying to copy from a source that does not exists error`

### Expected
A new library template is created

### Minimal Reproduction of Problem
```markdown
➜  ReactApps yo react-component-library                               
? Your project name test-project-react-image-drag-and-drop
? Some project description fadsfasdf
? What package manager do you want to use? npm
? What library do you want to use to test? Jest + React Testing Library
? Do you want to add storybook? Yes
events.js:187
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-react-component-library/generators/scaffold/templates/.gitignore
```

### Environment
```markdown
generator version: 1.5.1
node version: v13.1.0
npm version: 6.12.1
OS: Mac OS
```

**Comment by raulfdm** [comment]
Hey @lgdelacruz92 , it's been long time since you open this PR.

I'm not sure if you're still interested in using it but I release today `v2.0.1` and it should work now! :)

Feel free to open this PR again if the problem persist.
